services:
  website:
    image: node:26
    container_name: letjsam-website
    volumes:
      - ./:/home/letsjam
    working_dir: /home/letsjam
    ports:
      - 5173:5173
      - 4173:4173
    restart: unless-stopped
    tty: true
