services:
  letsjam-website:
    build:
      context: .
    container_name: letsjam-website
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # cap_add:
    #   - CHOWN
    #   - DAC_READ_SEARCH
    #   - FOWNER
    #   - SETGID
    #   - SETUID
    volumes:
      - ./:/home/letsjam-website
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
  
  letsjam-db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    cap_drop:
      - ALL
    # cap_add:
    #   - CHOWN
    #   - DAC_READ_SEARCH
    #   - FOWNER
    #   - SETGID
    #   - SETUID
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: default
      POSTGRES_DB: letsjam
    ports:
      - 5432:5432
